### ISSUE TITLE
Support LINE emoji in messages

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-perl#119]
https://developers.line.biz/en/news/2020/04/14/messaging-api-update-april-2020/

**Comment by gugod** [comment]
Some notes here:

TextMessage type is updated to include an "sticon" attribute that represents an "emoji". See the reference here: <https://developers.line.biz/en/reference/messaging-api/#text-message> 

"sticon" is the old term for emoji, but it looks like we will still be using this "sticon" for a little bit longer. There is a fixed list of usable sticon IDs, although I don't think we need to enumerate all of those. A loose regex should suffice the purpose of validation.

This should be trivial enough to be finished in a singe commit and be part of the next release.

**Comment by gugod** [comment]
https://developers.line.biz/ja/news/2020/04/14/messaging-api-update-april-2020/

Note: The attribute "sticon" is changed to be "emoji"

**Comment by gugod** [comment]
This is released in 1.17
