### ISSUE TITLE
Flex Message Support

### ISSUE THREAD

**Issue by tokuhirom** [line/line-bot-sdk-perl#27]
[LINE Flex Message](https://developers.line.me/en/docs/messaging-api/using-flex-messages/)

**Comment by gugod** [comment]
It appears to me that this issue is about making a builder for Flex Message, similar to ImagemapMessage, TemplateMessage, etc.

In order to do that, it is required to implement a complete tree of different components so we do can something like:

```perl
# LBAB = short for Line::Bot::API::Builder
my $message = LBAB::FlexMessage->new( type => "bubble" );
$messgae->set_body(
    LBAB::BoxComponent->(
        type => "text",
        text => "Hello World"
    )
)->set_hero(
    LBAB::ImageComponent->(
        url => "https://example.com/hello.jpg"
    )
);
```

Would this full-blown OO approach be a good one for how this should implemented ?

**Comment by tokuhirom** [comment]
Builder approach is good, of course. But the implementation cost and maintenance cost is high.
In my opinion, most users don't want to use builders on Lightweight language. If there's an interface to pass a simple hash/array structure, it's good enough.

**Comment by gugod** [comment]
@tokuhirom I second that thought as I also prefer thin client.

I beleve that the FlexMessage can already be delivered by the methods `reply_message`, `push_message` etc. I'll try to come up with some examples .

**Comment by gugod** [comment]
Added an example program that push a hand-crafted Flex Message. See https://github.com/line/line-bot-sdk-perl/blob/master/eg/push-flex-hello.pl

**Comment by tokuhirom** [comment]
Sorry for my late reply. I'll close this issue.
