### ISSUE TITLE
[Feature] Rich menu for multiple users

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-perl#53]
Link/Unlink rich menu to/from multiple users.
Reference:
https://developers.line.biz/en/docs/messaging-api/using-rich-menus/#link-rich-menu-to-users
https://developers.line.biz/en/docs/messaging-api/using-rich-menus/#unlink-rich-menu-from-users

**Comment by gugod** [comment]
The PR for this is #60

**Comment by gugod** [comment]
Released in 1.08.
