### ISSUE TITLE
Flex 1 update

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-perl#81]
updated: by @gugod 

Announcement: https://developers.line.biz/en/news/2019/08/28/flex-message-update-1-released/
Spec: https://developers.line.biz/en/docs/messaging-api/using-flex-messages/#introduction

The spec of Flex message was updated to include more types of layout. The overall container looks the same -- it is still a bunch of nested JSON objects.

Actionables:
- [x] Take the official examples in the spec and verify that it works by sending it through our SDK
- [x] (If needed) Translate our existing examples to the updated version
- [x] Update our Type Constraints (if any) to match the "Update 1"
- [x] Verify if we need to remove something.

**Comment by gugod** [comment]
We don't have any Type Constraints in place to check out-going messages -- so I guess we don't need to do anything in there -- I'll just mark that TODO as complete. :)

**Comment by gugod** [comment]
All done and released.
