### ISSUE TITLE
Domain name change from api.line.me to api-data.line.

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-perl#87]
The domain name of certain Messaging API endpoints has been changed from api.line.me to api-data.line.me.

https://developers.line.biz/en/news/#notice-of-domain-name-change-for-certain-endpoints-2019-11-08

Transition period
2019-11-08 - April 30, 2020

Once the transition period ends, accessing an endpoint of the old domain will return a 404 status code.

**Comment by gugod** [comment]
@bedoshi お願いします 🙇

**Comment by gugod** [comment]
Semi-related: PR #83 (Define constants for API endpoints)

**Comment by gugod** [comment]
The work ( PR #88 ) for this issue is merged into master and will be part of next release.

**Comment by gugod** [comment]
Release, and done done.
