### ISSUE TITLE
Support stay event added to beacon event

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-perl#90]
> In the Messaging API beacon event, a stay event has been added to indicate that the user is staying in the covered area of the beacon.

Messaging api reference: https://developers.line.biz/en/reference/messaging-api/#beacon-event
News: https://developers.line.biz/en/news/#a-stay-event-was-added-to-beacon-event-2019-12-06

**Comment by gugod** [comment]
The current implementation of `BeaconDetection.pm` already support this and  I believe no more work needs to be done for this.
